# Generated by Django 5.2.14 on 2026-05-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('flagged', 'Flagged')], default='draft', max_length=20)),
                ('ai_analysis', models.TextField(blank=True)),
                ('ai_score_impact', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('initiated_by', models.CharField(max_length=255)),
                ('handed_to', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_chain_complete', models.BooleanField(default=True)),
                ('ai_flag_reason', models.TextField(blank=True)),
            ],
        ),
    ]
