# Generated by Django 5.2.14 on 2026-05-12 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskentry',
            name='daily_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_entries', to='logs.dailylog'),
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['worker', 'date'], name='logs_dailyl_worker__f47294_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['worker', 'status'], name='logs_dailyl_worker__270e1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailylog',
            constraint=models.UniqueConstraint(fields=('worker', 'date'), name='logs_worker_date_unique'),
        ),
        migrations.AddIndex(
            model_name='taskentry',
            index=models.Index(fields=['daily_log', 'start_time'], name='logs_tasken_daily_l_95fe21_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskentry',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lte', models.F('end_time'))), name='logs_task_start_before_or_equal_end'),
        ),
    ]
