# Generated by Django 5.2.14 on 2026-05-12 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyscore',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scorededuction',
            name='monthly_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='scoring.monthlyscore'),
        ),
        migrations.AddIndex(
            model_name='monthlyscore',
            index=models.Index(fields=['worker', 'year', 'month'], name='scoring_mon_worker__0f308a_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyscore',
            index=models.Index(fields=['is_flagged'], name='scoring_mon_is_flag_998dd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlyscore',
            constraint=models.UniqueConstraint(fields=('worker', 'year', 'month'), name='scoring_worker_year_month_unique'),
        ),
        migrations.AddIndex(
            model_name='scorededuction',
            index=models.Index(fields=['monthly_score', 'applied_at'], name='scoring_sco_monthly_30a2c6_idx'),
        ),
        migrations.AddIndex(
            model_name='scorededuction',
            index=models.Index(fields=['reason'], name='scoring_sco_reason_682fde_idx'),
        ),
    ]
