# Generated by Django 5.2.14 on 2026-05-12 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedworker',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='hr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flaggedworker',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_workers', to='reports.monthlyreport'),
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['hr', 'year', 'month'], name='reports_mon_hr_id_547880_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlyreport',
            constraint=models.UniqueConstraint(fields=('hr', 'year', 'month'), name='reports_hr_year_month_unique'),
        ),
        migrations.AddIndex(
            model_name='flaggedworker',
            index=models.Index(fields=['review_completed', 'physical_review_required'], name='reports_fla_review__320fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='flaggedworker',
            index=models.Index(fields=['worker'], name='reports_fla_worker__322363_idx'),
        ),
        migrations.AddConstraint(
            model_name='flaggedworker',
            constraint=models.UniqueConstraint(fields=('report', 'worker'), name='reports_flagged_worker_unique'),
        ),
    ]
