# Generated by Django 5.2.14 on 2026-05-12 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryadvancerequest',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarydisbursement',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_disbursements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workerbankaccount',
            name='worker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='salaryadvancerequest',
            index=models.Index(fields=['worker', 'year', 'month'], name='payments_sa_worker__c6de78_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryadvancerequest',
            index=models.Index(fields=['status'], name='payments_sa_status_7ef799_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydisbursement',
            index=models.Index(fields=['worker', 'year', 'month'], name='payments_sa_worker__262ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydisbursement',
            index=models.Index(fields=['status'], name='payments_sa_status_18f87c_idx'),
        ),
        migrations.AddConstraint(
            model_name='salarydisbursement',
            constraint=models.UniqueConstraint(fields=('worker', 'year', 'month'), name='payments_worker_year_month_disbursement_unique'),
        ),
        migrations.AddIndex(
            model_name='workerbankaccount',
            index=models.Index(fields=['bank_code'], name='payments_wo_bank_co_55ade7_idx'),
        ),
        migrations.AddIndex(
            model_name='workerbankaccount',
            index=models.Index(fields=['is_verified'], name='payments_wo_is_veri_19e88b_idx'),
        ),
    ]
